from enum import Enum

NYU_VIOLET = "#57068c"
ULTRA_VIOLET = "#8900e1"
MEDIUM_VIOLET1 = "#702b9d"
MEDIUM_VIOLET2 = "#7b5aa6"
LIGHT_VIOLET1 = "#ab82c5"
LIGHT_VIOLET2 = "#eee6f3"
DEEP_VIOLET = "#330662"
BLACK = "#000000"
DARK_GRAY = "#404040"
MEDIUM_GRAY1 = "#6d6d6d"
MEDIUM_GRAY2 = "#b8b8b8"
MEDIUM_GRAY3 = "#d6d6d6"
LIGHT_GRAY = "#f2f2f2"
WHITE = "#ffffff"
MAGENTA = "#fb0f78"
TEAL = "#009b8a"
BLUE = "#59b2d1"
YELLOW = "#f4ec51"


# as an enum
class Color(Enum):
    NYU_VIOLET = NYU_VIOLET
    ULTRA_VIOLET = ULTRA_VIOLET
    MEDIUM_VIOLET1 = MEDIUM_VIOLET1
    MEDIUM_VIOLET2 = MEDIUM_VIOLET2
    LIGHT_VIOLET1 = LIGHT_VIOLET1
    LIGHT_VIOLET2 = LIGHT_VIOLET2
    DEEP_VIOLET = DEEP_VIOLET
    BLACK = BLACK
    DARK_GRAY = DARK_GRAY
    MEDIUM_GRAY1 = MEDIUM_GRAY1
    MEDIUM_GRAY2 = MEDIUM_GRAY2
    MEDIUM_GRAY3 = MEDIUM_GRAY3
    LIGHT_GRAY = LIGHT_GRAY
    WHITE = WHITE
    MAGENTA = MAGENTA
    TEAL = TEAL
    BLUE = BLUE
    YELLOW = YELLOW
